/alert("This is the 😎Epic Gamer Hub😎. Click on close if you are worthy to continue.")
alert("ARE YOU SUREEEEEE!")
alert("ok then answer this on question to proceed")
alert("What is the oppisite of open?")
alert("WOW! You have answered it correctly now Im going to try to scare you.")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("⚠️THIS WEBSITE CONTAINS VIRUS⚠️")
alert("bruh")
alert("bruh")
alert("bruh")
alert("bruh")
alert("bruh")
alert("bruh")
alert("bruh")
alert("You know I just dont want you to join right")
alert("bruh")
alert("bruh")
alert("bruh")
alert("bruh")
alert("bruh")
alert("bruh")
alert("bruh")
alert("WOW! you are now worthy to proceed.")/